#CircleCI version
version: 2.1
#Orbs for node and cli configuration
orbs:
  node: circleci/node@4.7.0
  aws-role-config: opensimsim/aws-role-config@1.1.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      #node valid version setup
      - node/install
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Get and install node version manager.
          command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - run:
          name: Install Node version 14.17.0 using NVM and set as default
          command: |
            nvm install 14.17.0
            nvm alias default 14.17.0
      - run:
          name: Verify new version of node
          command: node -v
      - checkout
      #cli setup
      - aws-cli/setup
      - eb/setup
      #Frontend jobs
      - run:
          name: Front-End Install
          command: |
            cd udagram
            npm run frontend:install
            cd ..
      - run:
          name: Front-End Build
          command: |
            cd udagram
            npm run frontend:build
            cd ..
      - run:
          name: Front-End Deploy
          command: |
            cd udagram
            npm run frontend:deploy
            cd ..
      #Backend jobs
      - run:
          name: Back-End Install
          command: |
            cd udagram
            npm run backend:install
            cd ..
      - run:
          name: Back-End Build
          command: |
            cd udagram
            npm run backend:build
            cd ..
      - run:
          name: Back-End Deploy
          command: |
            cd udagram
            npm run backend:deploy
            cd ..
            
workflows:
  all:
  jobs:
      - build:
          filters:
            branches:
             only: master
